on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-11, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm ci
      - run: npm run webpack
      - run: xvfb-run -a npm test
        if: runner.os == 'Linux'
      - run: npm test
        if: runner.os != 'Linux'
      - name: Upload log file to workflow artifacts on error
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: extension.log
          path: test-workspace/hls.log

